apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3  # Number of nginx pods for high availability
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:             # Container configuration inside each pod
      - name: nginx        
        image: nginx:latest   # use nginx:latest for version1 deployment,nginx:1.21.3 image for version2 deployment
        ports:
        - containerPort: 80